
import { AgentType } from './types';

export const AGENT_COLORS = {
  [AgentType.USER]: 'bg-slate-700 border-slate-600',
  [AgentType.ORCHESTRATOR]: 'bg-fuchsia-900/50 border-fuchsia-700 text-fuchsia-200',
  [AgentType.PLANNER]: 'bg-indigo-900/50 border-indigo-700 text-indigo-200',
  [AgentType.GENERAL_PLANNER]: 'bg-blue-900/50 border-blue-700 text-blue-200',
  [AgentType.NEURO_PLANNER]: 'bg-indigo-900/50 border-indigo-700 text-indigo-200',
  [AgentType.PLAN_VALIDATOR]: 'bg-rose-900/50 border-rose-700 text-rose-200',
  [AgentType.PREPROCESSOR]: 'bg-teal-900/50 border-teal-700 text-teal-200',
  [AgentType.EXECUTOR]: 'bg-emerald-900/50 border-emerald-700 text-emerald-200',
  [AgentType.RESEARCHER]: 'bg-purple-900/50 border-purple-700 text-purple-200',
  [AgentType.SYSTEM]: 'bg-gray-800 border-gray-700 text-gray-400',
};

export const MOCK_CSV_DATA = `ID,DX,Age,Sex,Amyloid_lS_orbital_med,Amyloid_lG_and_S_occipital_inf,Tau_Global
001,CN,72,F,1.1,1.05,0.8
002,CN,75,M,1.05,1.02,0.82
003,MCI,71,M,1.4,1.15,1.1
004,AD,80,F,1.8,1.45,1.5
005,MCI,68,F,1.35,1.12,1.05
006,CN,74,M,1.08,1.01,0.78
007,AD,82,M,1.9,1.50,1.6
008,LMCI,76,F,1.5,1.25,1.3
009,EMCI,69,M,1.25,1.10,0.95
010,AD,79,F,1.75,1.48,1.55
011,CN,70,F,1.02,0.99,0.75
012,MCI,73,M,1.38,1.20,1.15
013,LMCI,77,F,1.55,1.30,1.35
014,CN,71,M,1.06,1.03,0.81
015,AD,85,F,2.0,1.60,1.7
`;

export const PROMPTS = {
  ORCHESTRATOR_CLASSIFY: (query: string) => `
    You are an Orchestrator Agent for a neuroimaging analysis system.
    
    Classify the User Query into one of two categories:
    1. "RESEARCH": The user wants to analyze data, inspect columns, perform statistics, find correlations, compare groups, or search for literature.
    2. "GENERAL": The user wants to modify the visualization (e.g., change color, title, size), ask a general question unconnected to the dataset, or perform simple UI tasks.

    User Query: "${query}"

    Return strictly a JSON object: { "category": "RESEARCH" } or { "category": "GENERAL" }
  `,

  GENERAL_PLANNER: (query: string, toolDescriptions: string, feedback: string) => `
    You are a General Task Planner.
    User Query: "${query}"
    
    Available Tools:
    ${toolDescriptions}
    
    Task: Create a plan to satisfy the user request using the available tools.
    If the user wants to change visualization style (color, title, dot size), use the MODIFY_VISUALIZATION tool.
    ${feedback ? `
    IMPORTANT: A previous version of the plan was REJECTED by the Validator with these errors:
    ${feedback}
    
    Please correct the plan based on this feedback.
    ` : ""}

    You must return a valid JSON object with the following structure:
    {
      "analysis_steps": [
        {
          "step_id": 1,
          "tool": "TOOL_NAME", 
          "description": "Description of the step",
          "parameters": {
            "key": "value"
          }
        }
      ],
      "rationale": "Reasoning for the plan"
    }
  `,

  NEURO_PLANNER: (query: string, dataContext: string, allToolDescs: string, feedback: string) => `
    You are a Planner Agent in a neuroimaging multi-agent system.
    User Query: "${query}"
    Data Context: The user has uploaded a dataset with these columns: ${dataContext}.
    
    Task: Break down the query into logical analysis steps using the available tools.
    
    IMPORTANT: If the user asks for correlation involving a categorical column (like DX, Sex), you MUST first use TRANSFORM_DATA to convert it to numbers, then use the new column (e.g. DX_numeric) for correlation.
    ${feedback ? `
    IMPORTANT: A previous version of the plan was REJECTED by the Validator with these errors:
    ${feedback}
    
    Please fix the plan by correcting tool names or parameter column names based on the feedback and dataset context.
    ` : ""}

    Available Tools:
    ${allToolDescs}

    You must return a valid JSON object with the following structure:
    {
      "analysis_steps": [
        {
          "step_id": 1,
          "tool": "TOOL_NAME", 
          "description": "Description of the step",
          "parameters": {
            "target_column": "...",
            "x_column": "...",
            "y_column": "..."
          }
        }
      ],
      "rationale": "Reasoning for the plan"
    }
  `,

  PLAN_VALIDATOR: (existingColumns: string[], toolManifest: string, planJson: string) => `
    You are a Plan Validator Agent. 
    Your job is to strictly verify the execution plan generated by a Planner.

    Dataset Columns: ${JSON.stringify(existingColumns)}
    Tool Whitelist (Allowed Tools & Schemas): ${toolManifest}

    Validation Rules:
    1. Tool Existence: The "tool" field in each step must exactly match one of the names in the Tool Whitelist (e.g., "DATA_INSPECT", "TRANSFORM_DATA", "CORRELATION_ANALYSIS").
    2. Parameter Validity:
       a) Column References: If a parameter key (like "column", "x_column", "y_column", "group_column", "target_column") is used, its value MUST either exist in the "Dataset Columns" list OR be a virtual numeric column created by a preceding "TRANSFORM_DATA" step (e.g., if step 1 transforms "DX", step 2 can use "DX_numeric").
       b) Schema Adherence: All other parameters (e.g., "title", "color", "description") must follow the types/definitions in the Tool Whitelist.
    3. Follow Plan Order: You must judge a step based on expected changes made by the previous steps.
    4. Completeness: Ensure all "required" parameters for a tool are present in the step.

    Execution Plan:
    ${planJson}

    Return strictly a JSON object:
    {
      "valid": boolean,
      "errors": ["list", "of", "specific", "error", "messages"],
      "suggestions": "Actionable advice to fix the plan if invalid."
    }
  `,

  PREPROCESSOR_MAPPING: (column: string, values: string[]) => `
    You are a Data Preprocessor Agent in a neuroimaging study.
    Column Name: "${column}"
    Unique Values: ${JSON.stringify(values)}
    
    Task: Create a logical numeric mapping for these categorical values and provide a short rationale.
    - If it looks like disease stages (e.g. CN, MCI, AD), map them ordinally (e.g. CN=0, MCI=1, AD=2).
    - If it is binary (e.g. Sex F/M), map to 0/1.
    - Otherwise, assign integers based on neuroscience knowledge.
    
    Return ONLY a valid JSON object: { "mapping": { "Val1": 0, "Val2": 1, ... }, "rationale": "Short explanation of the mapping strategy." }
  `,

  RESEARCHER_INSIGHTS: (results: string) => `
    You are a Researcher Agent in a neuroimaging study.
    Review the following analysis results provided by the Executor:
    ${results}

    Provide a scientific interpretation. 
    1. Are the p-values significant?
    2. What does the correlation coefficient imply?
    3. Suggest one follow-up analysis or a relevant neuroimaging keyword to search next.
    
    IMPORTANT: When you refer to a specific analysis step (e.g. Step 1, Step 2), use the syntax [[Step N]] (e.g. [[Step 1]]) so that the UI can create a link to that specific result card.
    
    Example: "As seen in [[Step 1]], the amyloid distribution is skewed..."

    Keep it concise (max 3 paragraphs).
  `,

  LITERATURE_SEARCH: (topic: string) => `
    You are a Literature Search Agent.
    Topic: "${topic}"
    
    Generate a list of 3-4 plausible sounding neuroimaging citations (Author, Year, Title, Journal) related to this topic.
    Return a valid JSON array of objects with keys: title, authors, year, journal, summary.
  `
};
